config/routes.rb
Rails.application.routes.draw do
  root to: 'home#home'

  resources :scenes
  resources :users, :only => [:new, :create]
  resources :user_sessions, :only => [:new, :create, :destroy]
  resources :user_scenes, :only => [:create]

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/scene.rb
class Scene < ActiveRecord::Base
	has_many :child_scenes, class_name: "Scene", foreign_key: "parent_scene_id"
	belongs_to :parent_scene, class_name: "Scene"
	has_many :user_scenes
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :user_scenes
  has_many :scenes, :through => :user_scenes

  validates :password, length: { minimum: 8 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true
end

app/models/user_scene.rb
class UserScene < ActiveRecord::Base
	belongs_to :user
	belongs_to :scene
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :require_login

  private
	def not_authenticated
	  redirect_to login_path, alert: "Please login first"
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_filter :require_login

	def home
		@scenes = Scene.all
	end
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController

  def index
    @scenes = Scene.all
  end

  def show
  	@scene = Scene.find(params[:id])
    @clue_scenes = current_user.scenes.where(:relevant_clue => true)
  end

  def new
  	@scene = Scene.new
  end

  def create
  	@scene = Scene.new(scene_params)

  	if @scene.save
  		redirect_to scenes_url
  	else
  		render :new
  	end
  end

  def edit
  	@scene = Scene.find(params[:id])

  	if @scene
  		render :edit
  	else
  		flash("This scene id does not exist!")
  	end
  end

  def update
  	@scene = Scene.find(params[:id])

  	if @scene.update_attributes(scene_params)
  		redirect_to scene_path(@scene)
  	else
  		render :edit
  	end
  end

  def destroy
  	@scene = Scene.find(params[:id])
  	@scene.destroy
    redirect_to scenes_url
  end

  private
  def scene_params
  	params.require(:scene).permit(:date, :time, :location, :parent_scene_id, :choice, :story_body, :relevant_clue, :notebook_entry)
  end

end

app/controllers/user_scenes_controller.rb
class UserScenesController < ApplicationController
	def create
		# if the current scene the user is on has already been logged in database, then it won't be repeated
		# 1. find scene_id in database of all users' scenes
		# 1MMM. find the current Scene among all Scenes this user has visited, if it exists
		@scene = Scene.find(params[:scene_id])
		@existing_scene = current_user.scenes.include?(@scene)

		# 2. If no existing scene was found, create a new one
		if !@existing_scene
			@user_scene = UserScene.new
			@user_scene.user = current_user
			@user_scene.scene_id = params[:scene_id]

			if @user_scene.save
				redirect_to scene_path(params[:scene_id])
			else
				# render :new
			end
		else
			redirect_to scene_path(params[:scene_id])
		end
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
  	@scenes = Scene.all
    if @user = login(params[:email], params[:password], params[:remember_me])
      redirect_back_or_to "/scenes/#{@scenes.first.id}", notice: 'Login successful'
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_filter :require_login, only: [:index, :new, :create]

def new
	@user = User.new
end

def create
	@scenes = Scene.all
  @user = User.new(user_params)
  	if @user.save
      auto_login(@user)
  		redirect_to "/scenes/#{@scenes.first.id}", :notice => "Successfully signed up!"
  	else
  		render "new"
  	end
end

private
  def user_params
  	params.require(:user).permit(:character_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/helpers/user_scenes_helper.rb
module UserScenesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/home.html.erb
<h1 class="headline">This is the Doctor speaking...</h1>

<div class="begin" ><%= link_to( "Begin Story", "/scenes/#{@scenes.first.id}" ) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<% javascript_include_tag "vendor/modernizr" %>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	  <title>This is the Doctor speaking...</title>
	  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	  <link href='http://fonts.googleapis.com/css?family=Sigmar+One' rel='stylesheet' type='text/css'>
	  <link href='http://fonts.googleapis.com/css?family=Cutive+Mono' rel='stylesheet' type='text/css'>
	  <link href='http://fonts.googleapis.com/css?family=Marck+Script' rel='stylesheet' type='text/css'>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>


	<div>
		<p id="notice"><%= flash[:notice] %></p>
	    <p id="alert"><%= flash[:alert] %></p>
	</div>

	<div class="container">

		<%= yield %>

	</div>

	<div id="nav">
		<% if current_user %>
	      <%= link_to "Logout", :logout, method: :post %>
	    <% else %>
	      <%= link_to "Register", new_user_path %> |
	      <%= link_to "Login", :login %>
	    <% end %>
	</div>
	</body>
</html>

app/views/scenes/index.html.erb
<h1>Admin:  All Current Scenes</h1>

<% @scenes.each do |scene| %>
	<p>	<%= scene.id %><br />
	<%= scene.date %><br />
	<%= scene.time %><br />
	<%= scene.location %><br />
	<%= scene.story_body %><br />
	<%= link_to "Show the scene.", "scenes/#{scene.id}" %></p>
<% end %>

app/views/scenes/show.html.erb
<div class="off-canvas-wrap" data-offcanvas>
  <div class="inner-wrap">

    <a class="right-off-canvas-toggle" href="#" >Open Your Notebook</a>

    <!-- Off Canvas Menu -->
    <aside class="right-off-canvas-menu">
        <!-- whatever you want goes here -->
        <ul class="notebook-entries"><% @clue_scenes.each do |clue_scene| %>
             <li><%= clue_scene.notebook_entry %></li>
            <% end %>
          </ul>
    </aside>

    <!-- main content goes here -->

    <h1 class="title-text"><%= @scene.date %>, <%= @scene.time %>, <%= @scene.location %><br /></h1>
  	<p class="story-body"><%= @scene.story_body %></p>

	<% @scene.child_scenes.each do |child| %>
		<%= form_for UserScene.new do |f| %>
			<%= hidden_field_tag :scene_id, child.id %>
			<div class="botton">
	  		<%= f.submit child.choice, class:'button' %>
	  	</div>
    <% end %>
  <% end %>

	<% if !@scene.child_scenes.any? %>
		<div class="back">
			<%= link_to "Back", :back %>
		</div>
	<% end %>

  <!-- close the off-canvas menu -->
  <a class="exit-off-canvas"></a>

  </div>
</div>

app/views/user_sessions/_form.html.erb
<div class="row">
	<div class="large-6 columns">
		<h1 class="login">Login</h1>
		<%= form_tag user_sessions_path, :method => :post do %>

		  <div class="field">
		    <%= label_tag :email %><br />
		    <%= text_field_tag :email %>
		  </div>
		  <div class="field">
		    <%= label_tag :password %><br />
		    <%= password_field_tag :password %>
		  </div>
		  <div class="field">
		    <%= check_box_tag :remember_me %><br />
		    <%= label_tag :remember_me %>
		  </div>
		  <div class="actions">
		    <%= submit_tag "Login", class: 'button tiny left' %>
		  </div>
		<% end %>
	</div>
<div>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class ="error_messages">
			<h2>Sign up failed!</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field">
     <%= f.label :character_name %><br />
     <%= f.text_field :character_name %>
  	</div>

	<div class="field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %><br/>
		<%= f.password_field :password_confirmation %>
	</div>

	<div class="actions"><%= f.submit %></div>

<% end %>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= render 'form' %>